
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_SPEAKER: ROLE_USER
        ROLE_STUDENT: ROLE_USER
        ROLE_HIGH_SCHOOL: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: login
                check_path: login
                provider:     app_user_provider
                use_forward:  false
                failure_path: null
            logout:
                path: logout
                target: home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2419200 # 1 month in seconds
                signature_properties: [ 'password', 'email' ]
            custom_authenticator: App\Security\LoginAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/.*, role: PUBLIC_ACCESS, requires_channel: https }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
