vich_uploader:
    db_driver: orm

    mappings:
        resource_file:
            uri_prefix: /data/resources
            upload_destination: '%kernel.project_dir%/data/resources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

