version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_PASSWORD: root
    volumes: 
      - database_data:/var/lib/mysql

volumes:
  database_data:
